// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5G2sKmH72yLx4Bv55IBRsF5zp7yrjHIo',
    appId: '1:485223133823:web:eb0c554891b70c1863454a',
    messagingSenderId: '485223133823',
    projectId: 'log-in-839a8',
    authDomain: 'log-in-839a8.firebaseapp.com',
    storageBucket: 'log-in-839a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEJieS5-w4nS_cCMMpPj0ecTyxMRx7NN4',
    appId: '1:485223133823:android:a502fb50473fe10863454a',
    messagingSenderId: '485223133823',
    projectId: 'log-in-839a8',
    storageBucket: 'log-in-839a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFG3SZAV4NVwVthPXZzLUfJ6_GpOYjoNo',
    appId: '1:485223133823:ios:d95cba9a9505502963454a',
    messagingSenderId: '485223133823',
    projectId: 'log-in-839a8',
    storageBucket: 'log-in-839a8.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFG3SZAV4NVwVthPXZzLUfJ6_GpOYjoNo',
    appId: '1:485223133823:ios:d95cba9a9505502963454a',
    messagingSenderId: '485223133823',
    projectId: 'log-in-839a8',
    storageBucket: 'log-in-839a8.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
